// Generated by https://quicktype.io
import { Movie } from './movieInterface';

export interface SearchMovie {
    page: number;
    results: Movie[];
    total_pages: number;
    total_results: number;
}

enum OriginalLanguage {
    En = 'en',
    Es = 'es',
    Pl = 'pl',
    Pt = 'pt',
}
